# workflow uruchamia się przy pushu, pull requestach i ręcznie
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]  # testujemy na dwóch wersjach Pythona

    steps:
      # pobranie kodu repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # ustawienie wybranej wersji Pythona
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # uruchomienie testów z folderu test
      - name: Run tests
        run: pytest test/
        env:
         PYTHONPATH: .
